#!/usr/bin/env node
/**
 * Emits the landing page's design-system assets.
 *
 * The landing lives in public/, outside the bundle and outside the service worker, so it
 * cannot `@import` design-system/tokens/tokens.css the way src/index.css does. The obvious
 * workaround is what public/calculadoras/ did: hand-copy a :root block. That block is now
 * stale — it still declares Inter Variable and --color-tax, both retired in August — which
 * is exactly the debt design-system/docs/00-principles.md §A1 warns about.
 *
 * So nothing is copied by hand. This script mirrors the generated token file and the font
 * binaries verbatim, and `--check` fails when the mirror has drifted. Same shape as the
 * repo validator's R2.
 *
 * Usage: node scripts/landing-assets.mjs [--check]
 */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')

const TOKENS_SRC = join(root, 'design-system/tokens/tokens.css')
const TOKENS_OUT = join(root, 'public/landing/tokens.css')

// Only the Latin subsets. The landing is es-CO; latin-ext covers the accents Spanish
// actually uses and the rest would be weight the page never serves.
const FONTS = ['rethink-sans-latin-wght-normal.woff2', 'rethink-sans-latin-ext-wght-normal.woff2']
const FONT_SRC_DIR = join(root, 'node_modules/@fontsource-variable/rethink-sans/files')
const FONT_OUT_DIR = join(root, 'public/landing/fonts')

const HEADER = `/* GENERATED by scripts/landing-assets.mjs — do not edit by hand.
   Mirror of design-system/tokens/tokens.css, which is itself generated from Figma.
   Run \`node scripts/landing-assets.mjs\` after any token change. */\n\n`

const sha = (buf) => createHash('sha256').update(buf).digest('hex')

const tokens = readFileSync(TOKENS_SRC, 'utf8')
const expected = HEADER + tokens

const drifted = []

if (!existsSync(TOKENS_OUT) || readFileSync(TOKENS_OUT, 'utf8') !== expected) {
  if (check) drifted.push('public/landing/tokens.css')
  else {
    mkdirSync(dirname(TOKENS_OUT), { recursive: true })
    writeFileSync(TOKENS_OUT, expected)
  }
}

mkdirSync(FONT_OUT_DIR, { recursive: true })
for (const file of FONTS) {
  const from = join(FONT_SRC_DIR, file)
  const to = join(FONT_OUT_DIR, file)
  if (!existsSync(from)) {
    console.error(`missing font source: ${from} — run npm ci`)
    process.exit(1)
  }
  if (!existsSync(to) || sha(readFileSync(to)) !== sha(readFileSync(from))) {
    if (check) drifted.push(`public/landing/fonts/${file}`)
    else copyFileSync(from, to)
  }
}

if (check) {
  if (drifted.length) {
    console.error('landing assets have drifted from their source:')
    for (const f of drifted) console.error(`  ${f}`)
    console.error('fix: node scripts/landing-assets.mjs')
    process.exit(1)
  }
  console.log('landing assets: in sync')
} else {
  console.log(`landing assets: tokens.css + ${FONTS.length} fonts written to public/landing/`)
}
